### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by youridijk** [screeny05/letterboxd-list-radarr#31]
I would like to see a docker image (or a Dockerfile to build a image locally) of this too (only the nodejs application, Redis should remain a different container)l to easier run it using docker compose.

**Comment by marothe** [comment]
Would love to see this too!

**Comment by screeny05** [comment]
Can somebody try this image and see if it works?

https://hub.docker.com/r/screeny05/letterboxd-list-radarr

Minimum viable configuration:

```
version: "3.8"
services:
    web:
        image: screeny05/letterboxd-list-radarr:1.0.1
        ports:
            - 5000:5000
        environment:
            - REDIS_URL=redis://redis:6379
        depends_on:
            - redis
    redis:
        image: redis:6.0
```
